repository: dynamsoft-docs/document-normalizer-docs
repositoryUrl: https://github.com/dynamsoft-docs/document-normalizer-docs/blob/main
docFullPath: https://www.dynamsoft.com/document-normalizer/docs
firstLevelUrl: /document-normalizer/docs/web
docHomePage: /document-normalizer/docs/core/introduction/

js: /document-normalizer/docs/web/programming/javascript/
js_api: /document-normalizer/docs/web/programming/javascript/api-reference/
js_release_notes: /document-normalizer/docs/web/programming/javascript/release-notes/
js_user_guide: /document-normalizer/docs/web/programming/javascript/user-guide/

enumerations_old: /document-normalizer/docs/web/programming/enumerations/
parameters_reference: /document-normalizer/docs/core/parameters/reference/
release_notes: /document-normalizer/docs/core/release-notes/

dcv_cpp_api: /capture-vision/docs/server/programming/cplusplus/api-reference/

useVersionTree: true

assets: /document-normalizer/docs/core/assets/
edit_icon: /document-normalizer/docs/core/assets/img-icon/edit-icon.png
smile_icon: /document-normalizer/docs/core/assets/img-icon/icon-smile.png
sad_icon: /document-normalizer/docs/core/assets/img-icon/icon-sad.png

baseurl: "/document-normalizer/docs/web"

download: "/document-normalizer/downloads/1000023-confirmation/"

plugins:
  - jemoji
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      layout: "default-layout"
      noTitleIndex: true
      needAutoGenerateSidebar: true
      needGenerateH3Content: true
  - scope:
      path: "Hide_Tree_Page.html"
    values:
      sitemap: false

url: "https://www.dynamsoft.com" # sitemap root
