# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for main and preview branch
  push:
    branches: 
    - main 
    - preview 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains jobs called "Build-Main" and "Build-Preview"
  Build-Main:
    if: ${{ github.ref == 'refs/heads/main' }}
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cd /home/ubuntu
          [ -d DDNDocJS ] && rm -rf DDNDocJS
          [ -d document-normalizer-docs-js ] && rm -rf document-normalizer-docs-js
          [ -d Docs-Template-Repo-Preview ] && rm -rf Docs-Template-Repo-Preview
          [ ! -d DDNDocJS ] && mkdir -p DDNDocJS
          git clone --depth 1 https://github.com/dynamsoft-docs/document-normalizer-docs-js.git document-normalizer-docs-js
          git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/Docs-Template-Repo.git Docs-Template-Repo-Preview
          cp -rfp ./document-normalizer-docs-js/* ./DDNDocJS/
          cp -rfp ./Docs-Template-Repo-Preview/* ./DDNDocJS/
          cd DDNDocJS && bundle install && bundle exec jekyll build

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_DYNAMSOFT_LOCAL_SERVER }}
          username: ${{ secrets.FTP_DYNAMSOFT_LOCAL_USER }}
          password: ${{ secrets.FTP_DYNAMSOFT_LOCAL_PASSWORD }}
          port: 21 
          local-dir: /home/ubuntu/DDNDocJS/_site/
          server-dir: /www.dynamsoft.com/document-normalizer/docs/web/

      - name: Trigger Webhook 
        run: | 
          curl -X POST -H "${{ secrets.WEBHOOK_USER }}" -H "${{ secrets.WEBHOOK_TOKEN }}" -H "Content-Type: application/json" -d "[\"/document-normalizer/docs/web/*\"]" ${{ secrets.WEBHOOK_URL }}

          
  Build-Preview:
    if: ${{ github.ref == 'refs/heads/preview' }}
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: clear space
        run: |
          cd /home/ubuntu 
          [ -d DDNDocJSPreview ] && rm -rf DDNDocJSPreview
          [ -d document-normalizer-docs-js-preview ] && rm -rf document-normalizer-docs-js-preview
          [ -d Docs-Template-Repo-Preview ] && rm -rf Docs-Template-Repo-Preview
          cd /home/ubuntu

      - name: Build the site
        run: |
          cd /home/ubuntu
          [ ! -d DDNDocJSPreview ] && mkdir -p DDNDocJSPreview
          git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/document-normalizer-docs-js.git document-normalizer-docs-js-preview
          git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/Docs-Template-Repo.git Docs-Template-Repo-Preview
          cp -rfp ./document-normalizer-docs-js-preview/* ./DDNDocJSPreview/
          cp -rfp ./Docs-Template-Repo-Preview/* ./DDNDocJSPreview/
          sed -i -e "1,3s/blob\/master$/blob\/preview/" \
          -e "1,3s/blob\/main$/blob\/preview/" /home/ubuntu/DDNDocJSPreview/_config.yml
          cd DDNDocJSPreview && bundle install && bundle exec jekyll build

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_TEST_SITE_SERVER }}
          username: ${{ secrets.FTP_TEST_SITE_USER }}
          password: ${{ secrets.FTP_TEST_SITE_PASSWORD }}
          port: 7500 
          local-dir: /home/ubuntu/DDNDocJSPreview/_site/
          server-dir: /www.dynamsoft.com/document-normalizer/docs/web/

          
